<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Admin-PC" name="com.uno.test.technician.Technician_ViewIncidentTest" tests="61" failures="4" timestamp="28 Dec 2018 11:51:25 GMT" time="2307.714" errors="2">
  <testcase name="VerifyIDTextBox" time="9.811" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="VerifyIDTextBox" time="26.293" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="VerifyIDTextBox" time="27.556" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <error type="org.openqa.selenium.ElementNotVisibleException" message="Element is not currently visible and so may not be interacted with
Command duration or timeout: 20.13 seconds
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b1534ae328c771e0856c93e187490ca824&#039;, time: &#039;2016-03-15 10:43:46&#039;
System info: host: &#039;Admin-PC&#039;, ip: &#039;192.168.1.22&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_161&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a30bb802-e67f-49aa-b348-697e7c8c78af">
      <![CDATA[org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 20.13 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Admin-PC', ip: '192.168.1.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a30bb802-e67f-49aa-b348-697e7c8c78af
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy15.sendKeys(Unknown Source)
at com.uno.pages.technician.Technician_ViewIncidentPage.verifyIdTextBox(Technician_ViewIncidentPage.java:373)
at com.uno.test.technician.Technician_ViewIncidentTest.VerifyIDTextBox(Technician_ViewIncidentTest.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Admin-PC', ip: '192.168.1.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
Driver info: driver.version: unknown
at <anonymous class>.fxdriver.preconditions.visible(file:///C:/Users/Admin/AppData/Local/Temp/anonymous5289669737802889329webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:10092)
at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///C:/Users/Admin/AppData/Local/Temp/anonymous5289669737802889329webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12644)
at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///C:/Users/Admin/AppData/Local/Temp/anonymous5289669737802889329webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Admin/AppData/Local/Temp/anonymous5289669737802889329webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:625)
]]>
    </error>
  </testcase> <!-- VerifyIDTextBox -->
  <testcase name="VerifyIDTextBox" time="11.949" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyAssetIdTextBox" time="9.197" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyAssetIdTextBox" time="11.654" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyAssetIdTextBox" time="30.800" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketIdTextBox" time="29.734" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketIdTextBox" time="53.140" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketIdTextBox" time="13.718" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketIdTextBox" time="10.568" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyStatusDropDown" time="20.670" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyStatusDropDown" time="35.472" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyStatusDropDown" time="35.907" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyStatusDropDown" time="17.571" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status value is not Same. expected [ReOpened] but found [11:38:00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status value is not Same. expected [ReOpened] but found [11:38:00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.uno.pages.technician.Technician_ViewIncidentPage.verifyStatusDropDown(Technician_ViewIncidentPage.java:575)
at com.uno.test.technician.Technician_ViewIncidentTest.verifyStatusDropDown(Technician_ViewIncidentTest.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyStatusDropDown -->
  <testcase name="verifyStatusDropDown" time="36.234" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyStatusDropDown" time="21.652" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Status value is not Same. expected [Paused] but found [11:21:00],
	Status value is not Same. expected [Paused] but found [09:34:34],
	Status value is not Same. expected [Paused] but found [14:52:49],
	Status value is not Same. expected [Paused] but found [12:06:00],
	Status value is not Same. expected [Paused] but found [17:51:00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Status value is not Same. expected [Paused] but found [11:21:00],
Status value is not Same. expected [Paused] but found [09:34:34],
Status value is not Same. expected [Paused] but found [14:52:49],
Status value is not Same. expected [Paused] but found [12:06:00],
Status value is not Same. expected [Paused] but found [17:51:00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.uno.pages.technician.Technician_ViewIncidentPage.verifyStatusDropDown(Technician_ViewIncidentPage.java:575)
at com.uno.test.technician.Technician_ViewIncidentTest.verifyStatusDropDown(Technician_ViewIncidentTest.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyStatusDropDown -->
  <testcase name="verifyTicketTypeDropDown" time="40.160" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="35.243" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="38.053" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="47.192" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="23.410" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="21.941" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="19.089" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="30.252" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="26.023" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="52.114" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyTicketTypeDropDown" time="22.318" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCTSDropDown" time="41.686" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCTSDropDown" time="39.796" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCTSDropDown" time="26.508" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out waiting for page load.
Command duration or timeout: 20.04 seconds
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b1534ae328c771e0856c93e187490ca824&#039;, time: &#039;2016-03-15 10:43:46&#039;
System info: host: &#039;Admin-PC&#039;, ip: &#039;192.168.1.22&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_161&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e31b2244-266b-48d8-ac24-55bad468b87b">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out waiting for page load.
Command duration or timeout: 20.04 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Admin-PC', ip: '192.168.1.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: e31b2244-266b-48d8-ac24-55bad468b87b
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy15.click(Unknown Source)
at com.uno.baseClass.BaseCode.setMyView(BaseCode.java:281)
at com.uno.test.technician.Technician_ViewIncidentTest.verifyCTSDropDown(Technician_ViewIncidentTest.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.TimeoutException: Timed out waiting for page load.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Admin-PC', ip: '192.168.1.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
Driver info: driver.version: unknown
at <anonymous class>.Utils.installClickListener/e<(file:///C:/Users/Admin/AppData/Local/Temp/anonymous6875511109047794779webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9372)
at <anonymous class>.WebLoadingListener/e(file:///C:/Users/Admin/AppData/Local/Temp/anonymous6875511109047794779webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:5142)
at <anonymous class>.WebLoadingListener/<(file:///C:/Users/Admin/AppData/Local/Temp/anonymous6875511109047794779webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:5150)
at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/Admin/AppData/Local/Temp/anonymous6875511109047794779webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:625)
]]>
    </error>
  </testcase> <!-- verifyCTSDropDown -->
  <testcase name="verifyCustomerDropDown" time="51.582" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCustomerDropDown" time="21.327" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCustomerDropDown" time="52.718" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCustomerDropDown" time="20.449" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCustomerDropDown" time="39.157" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCustomerDropDown" time="39.304" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyEngineerDropDown" time="37.109" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyEngineerDropDown" time="50.437" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyEngineerDropDown" time="35.933" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyEngineerDropDown" time="36.293" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyEngineerDropDown" time="34.971" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByRoleDropDown" time="19.979" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByRoleDropDown" time="19.376" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByRoleDropDown" time="35.408" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByRoleDropDown" time="34.961" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByRoleDropDown" time="21.782" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Created By Role value is not Same. expected [Customer] but found [],
	Created By Role value is not Same. expected [Customer] but found [],
	Created By Role value is not Same. expected [Customer] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Created By Role value is not Same. expected [Customer] but found [],
Created By Role value is not Same. expected [Customer] but found [],
Created By Role value is not Same. expected [Customer] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.uno.pages.technician.Technician_ViewIncidentPage.verifyCreatedByRoleDropDown(Technician_ViewIncidentPage.java:688)
at com.uno.test.technician.Technician_ViewIncidentTest.verifyCreatedByRoleDropDown(Technician_ViewIncidentTest.java:239)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCreatedByRoleDropDown -->
  <testcase name="verifyCreatedByDropDown" time="19.312" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByDropDown" time="34.532" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByDropDown" time="22.859" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByDropDown" time="30.830" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCreatedByDropDown" time="34.098" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCategoryDropDown" time="35.818" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifyCategoryDropDown" time="37.829" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifySubCategoryDropDown" time="36.272" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="verifySubCategoryDropDown" time="27.130" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="DisplayColumnHeader" time="561.382" classname="com.uno.test.technician.Technician_ViewIncidentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Column is not Match expected [Serial Number] but found [Serial No],
	Column is not Match expected [PO Amount] but found [Total PO Amount],
	Column is not Match expected [Amount Received Against PO] but found [Received PO Amount],
	Column is not Match expected [PI Amount] but found [Total PI Amount],
	Column is not Match expected [Amount Received Against PI] but found [Received PI Amount],
	Column is not Match expected [Count Of File Attachment] but found [No of File Attached],
	Column is not Match expected [Local Contact] but found [Customer Contact Name],
	Column is not Match expected [Local Contact No] but found [Customer Contact No],
	Column is not Match expected [Product Model No] but found [Product Model No.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Column is not Match expected [Serial Number] but found [Serial No],
Column is not Match expected [PO Amount] but found [Total PO Amount],
Column is not Match expected [Amount Received Against PO] but found [Received PO Amount],
Column is not Match expected [PI Amount] but found [Total PI Amount],
Column is not Match expected [Amount Received Against PI] but found [Received PI Amount],
Column is not Match expected [Count Of File Attachment] but found [No of File Attached],
Column is not Match expected [Local Contact] but found [Customer Contact Name],
Column is not Match expected [Local Contact No] but found [Customer Contact No],
Column is not Match expected [Product Model No] but found [Product Model No.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.uno.pages.technician.Technician_ViewIncidentPage.displayColumnHeader(Technician_ViewIncidentPage.java:1004)
at com.uno.test.technician.Technician_ViewIncidentTest.DisplayColumnHeader(Technician_ViewIncidentTest.java:295)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DisplayColumnHeader -->
  <testcase name="CountOfPagination" time="6.592" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="varifySearchFieldsInSearchTicketTab" time="4.723" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="checkDefaultOptionOfFilterTab" time="10.348" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
  <testcase name="DisplayAsPerArrowsOfPagination" time="29.492" classname="com.uno.test.technician.Technician_ViewIncidentTest"/>
</testsuite> <!-- com.uno.test.technician.Technician_ViewIncidentTest -->
